#!/bin/bash

# Part 1 (done)
 

 
 
 


# Part 2
freqtrade download-data --exchange binance --timeframes 5m --timerange 20250101-20250617 --pairs IOST/USDT ANKR/USDT RLC/USDT SFP/USDT STORJ/USDT RSX/USDT AUDIO/USDT DUSK/USDT BLZ/USDT LIT/USDT CTSI/USDT REEF/USDT NKN/USDT XVS/USDT ALPHA/USDT BNT/USDT BOND/USDT MBL/USDT TRB/USDT AKRO/USDT #(done)

 \
IDEX/USDT RAY/USDT PERP/USDT TLM/USDT RSR/USDT BEL/USDT DENT/USDT FOR/USDT SYS/USDT GTC/USDT \
STMX/USDT MDX/USDT ERN/USDT LQTY/USDT TVK/USDT AGLD/USDT FARM/USDT NMR/USDT ALICE/USDT VITE/USDT \
COTI/USDT FIS/USDT FRONT/USDT CVC/USDT DODO/USDT FIO/USDT UFT/USDT RAD/USDT CTK/USDT ARDR/USDT \
BAKE/USDT KNC/USDT POND/USDT PHA/USDT VTHO/USDT WRX/USDT REN/USDT DOCK/USDT BTS/USDT SXP/USDT \
QUICK/USDT OXT/USDT WING/USDT TROY/USDT STPT/USDT MDT/USDT SKL/USDT NULS/USDT HARD/USDT \
ARKM/USDT \
BADGER/USDT DGB/USDT HIVE/USDT XVG/USDT

# Part 3
freqtrade download-data --exchange binance --timeframes 5m --timerange 20250101-20250617 --pairs \
LAZIO/USDT CHESS/USDT ADX/USDT AUCTION/USDT MOVR/USDT CITY/USDT ENS/USDT QI/USDT PORTO/USDT POWR/USDT JASMY/USDT \
AMP/USDT PYR/USDT ALCX/USDT SANTOS/USDT BICO/USDT FLUX/USDT FXS/USDT VOXEL/USDT HIGH/USDT CVX/USDT PEOPLE/USDT \
SPELL/USDT JOE/USDT ACH/USDT IMX/USDT GLMR/USDT LOKA/USDT SCRT/USDT API3/USDT BTTC/USDT ACA/USDT XNO/USDT WOO/USDT \
ALPINE/USDT T/USDT ASTR/USDT GMT/USDT KDA/USDT APE/USDT BSW/USDT BIFI/USDT STEEM/USDT NEXO/USDT REI/USDT LDO/USDT \
OP/USDT LEVER/USDT STG/USDT LUNC/USDT GMX/USDT POLYX/USDT APT/USDT OSMO/USDT HFT/USDT PHB/USDT HOOK/USDT MAGIC/USDT \
HIFI/USDT RPL/USDT GNS/USDT SYN/USDT SSV/USDT LQTY/USDT USTC/USDT GAS/USDT GLM/USDT PROM/USDT QKC/USDT

# Part 4
freqtrade download-data --exchange binance --timeframes 5m --timerange 20250101-20250617 --pairs \
ARB/USDT RDNT/USDT WBTC/USDT EDU/USDT SUI/USDT PEPE/USDT FLOKI/USDT MAV/USDT PENDLE/USDT ARKM/USDT WBETH/USDT \
WLD/USDT FDUSD/USDT SEI/USDT CYBER/USDT ARK/USDT IQ/USDT NTRN/USDT TIA/USDT MEME/USDT ORDI/USDT BEAMX/USDT \
PIVX/USDT VIC/USDT BLUR/USDT VANRY/USDT AEUR/USDT JTO/USDT 1000SATS/USDT BONK/USDT ACE/USDT NFP/USDT AI/USDT \
XAI/USDT MANTA/USDT ALT/USDT JUP/USDT PYTH/USDT RONIN/USDT DYM/USDT PIXEL/USDT STRK/USDT PORTAL/USDT AXL/USDT \
WIF/USDT METIS/USDT AEVO/USDT BOME/USDT ETHFI/USDT ENA/USDT W/USDT TNSR/USDT SAGA/USDT TAO/USDT OMNI/USDT \
REZ/USDT BB/USDT NOT/USDT IO/USDT ZK/USDT LISTA/USDT ZRO/USDT G/USDT BANANA/USDT RENDER/USDT TON/USDT DOGS/USDT \
EURI/USDT SLF/USDT POL/USDT NEIRO/USDT TURBO/USDT 1MBABYDOGE/USDT CATI/USDT HMSTR/USDT EIGEN/USDT SCR/USDT \
BNSOL/USDT LUMIA/USDT KAIA/USDT COW/USDT CETUS/USDT PNUT/USDT ACT/USDT USUAL/USDT THE/USDT ACX/USDT ORCA/USDT \
MOVE/USDT ME/USDT VELODROME/USDT VANA/USDT 1000CAT/USDT PENGU/USDT BIO/USDT D/USDT AIXBT/USDT CGPT/USDT COOKIE/USDT \
S/USDT SOLV/USDT TRUMP/USDT ANIME/USDT BERA/USDT 1000CHEEMS/USDT TST/USDT LAYER/USDT HEI/USDT KAITO/USDT \
SHELL/USDT RED/USDT GPS/USDT EPIC/USDT BMT/USDT FORM/USDT XUSD/USDT NIL/USDT PARTI/USDT MUBARAK/USDT TUT/USDT \
BROCCOLI714/USDT BANANAS31/USDT GUN/USDT BABY/USDT ONDO/USDT BIGTIME/USDT VIRTUAL/USDT KERNEL/USDT WCT/USDT \
HYPER/USDT INIT/USDT SIGN/USDT STO/USDT SYRUP/USDT KMNO/USDT SXT/USDT NXPC/USDT AWE/USDT HAEDAL/USDT USD1/USDT \
HUMA/USDT A/USDT SOPH/USDT RESOLV/USDT HOME/USDT SPK/USDT

