@echo off
REM Activate your virtualenv if needed (optional)
REM call .venv\Scripts\activate.bat

REM Set common options
set TIMEFRAMES=1h 5m
set TIMERANGE=20250701-20250707
set EXCHANGE=binance
set DATADIR=user_data/data/binance_new


REM First batch
freqtrade download-data --timeframes %TIMEFRAMES% --timerange %TIMERANGE% --exchange %EXCHANGE% --pairs ^
BTC/USDT ETH/USDT BNB/USDT SOL/USDT XRP/USDT DOGE/USDT ADA/USDT TRX/USDT TIA/USDT VIRTUAL/USDT AVAX/USDT LINK/USDT SHIB/USDT DOT/USDT LTC/USDT BCH/USDT NEAR/USDT APT/USDT ^
UNI/USDT PEPE/USDT ICP/USDT ETC/USDT INJ/USDT AAVE/USDT HBAR/USDT VET/USDT MKR/USDT ATOM/USDT ARB/USDT IMX/USDT OP/USDT GRT/USDT ALGO/USDT ^
QNT/USDT EGLD/USDT AXS/USDT SAND/USDT MANA/USDT THETA/USDT NEO/USDT XTZ/USDT SUI/USDT ORDI/USDT VANA/USDT SUPER/USDT WBTC/USDT

REM Second batch
freqtrade download-data --timeframes %TIMEFRAMES% --timerange %TIMERANGE% --exchange %EXCHANGE% --pairs ^
CHZ/USDT MINA/USDT FLOW/USDT KAVA/USDT ENJ/USDT GALA/USDT ZIL/USDT ZK/USDT ZRO/USDT ZRX/USDT 1INCH/USDT 1000SATS/USDT ACA/USDT ACE/USDT ACH/USDT ACM/USDT ACT/USDT ACX/USDT ADX/USDT AEVO/USDT ^
AGLD/USDT AI/USDT ALCX/USDT ALICE/USDT ALPINE/USDT ALT/USDT AMP/USDT ANKR/USDT APE/USDT API3/USDT AR/USDT ARDR/USDT ARK/USDT ARKM/USDT ARPA/USDT ASR/USDT ASTR/USDT ATA/USDT ^
ATM/USDT AUCTION/USDT AUDIO/USDT AVA/USDT AXL/USDT BAKE/USDT BAND/USDT BAR/USDT BAT/USDT BB/USDT BEAMX/USDT

REM Third batch
freqtrade download-data --timeframes %TIMEFRAMES% --timerange %TIMERANGE% --exchange %EXCHANGE% --pairs ^
BEL/USDT BERA/USDT BICO/USDT BIFI/USDT BIGTIME/USDT BLUR/USDT BOME/USDT BONK/USDT BTTC/USDT C98/USDT CAKE/USDT CATI/USDT CELO/USDT CELR/USDT CETUS/USDT CFX/USDT CGPT/USDT ^
CHESS/USDT CHR/USDT CITY/USDT CKB/USDT COMP/USDT COTI/USDT COW/USDT CRV/USDT CTK/USDT CTSI/USDT CVC/USDT CVX/USDT CYBER/USDT DASH/USDT DATA/USDT DEGO/USDT DENT/USDT DEXE/USDT DF/USDT ^
DGB/USDT DIA/USDT DODO/USDT DOGS/USDT DUSK/USDT DYDX/USDT DYM/USDT EDU/USDT EIGEN/USDT ENA/USDT ENS/USDT EPIC/USDT ETHFI/USDT TON/USDT XLM/USDT

echo.
echo ✅ All data download commands completed.
pause
